[workspace]
members = [
    "crates/cansat-core",
    "crates/cansat-gps",
    "crates/cansat-stm32f4",
    "crates/cansat-test-utils",
    "crates/cansat-lora",
    "tools/lora-cli",
    "tools/flight-visualizer",
    "tools/dummy-lora-receiver",
    "xtask"
]
resolver = "2"