[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
DEFMT_LOG="info"

[tasks.clippy]
command = "cargo"
args = ["clippy", "${@}"]

[tasks.embed]
workspace = false
script_runner = "@shell"
script = '''
cd ${1} && cargo embed
'''