[alias]
xtask = "run --package xtask --release --"
lora-cli = "run --package lora-cli --release --"

[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }
XTASK_EMBED_DEFAULT = "cansat-stm32f4"
XTASK_TEST_EXCLUDE = "cansat-stm32f4"
DEFMT_LOG = "info"
